VALORES_CORRECTOS = {
    'BIENESTAR 20%': 'BIENESTAR',
    'BIENESTAR 100%': 'BIENESTAR',
    'BIENESTAR 80%': 'BIENESTAR',
    'BIENESTAR 50%': 'BIENESTAR',
    'COLEGIO LOS PINARES PP': 'COLEGIO',
    'COLEGIO UPB PP': 'COLEGIO',
    'COLEGIATURA DE COSMETOLOGIA': 'COLEGIATURA',
    'COMFENALCO BOTON DE PAGO': 'COMFENALCO',
    'COMFENALCO CLINICA OFTALMOLOGICA': 'COMFENALCO',
    'COMFENALCO CLINICA OFTALMOLOGICA MEDELLIN': 'COMFENALCO',
    'COMFENALCO GESTION HUMANA': 'COMFENALCO',
    'COMFENALCO NAVITRANS': 'COMFENALCO',
    'COMFENALCO PP': 'COMFENALCO',
    'CONVENIO PP': 'CONVENIO',
    'YOYO JEANS': 'EMPRESA',
    'TCL': 'EMPRESA',
    'NEW STETIC S.A': 'EMPRESA',
    'IEB': 'EMPRESA',
    'SATRACK': 'EMPRESA',
    'STOP': 'EMPRESA',
    'CLINICA ORLANT': 'CLINICA',
    'FUNDACION U DE A': 'UNIVERSIDAD',
    'UNIVERSIDAD ECCI PP': 'UNIVERSIDAD',
    'BIEESTAR 50%': 'BIENESTAR',
    'BIENENSTAR 50%': 'BIENESTAR',
    'BIENESTAR 50 %': 'BIENESTAR',
    'BIENESTAR 100 %': 'BIENESTAR',
    'BIENESTAR 80$': 'BIENESTAR',
    'BIENESTAR 80\'%': 'BIENESTAR',
    'BIENESTAR 80&': 'BIENESTAR',
    'BIENESTAR80%': 'BIENESTAR',
    'BIENSTAR 80%': 'BIENESTAR',
    'BINESTAR 80%': 'BIENESTAR',
    'ESTUDIANTE BIENESTAR 80%': 'BIENESTAR',
    'COLEGIO BARBARA MICARELLI': 'COLEGIO',
    'COLEGIO PIONEROS PP': 'COLEGIO',
    'COLEGIO LOS PIONEROS': 'COLEGIO',
    'COMFEALCO CONTRALORIA': 'COMFENALCO',
    'COMFENALCO CONTROLORIA': 'COMFENALCO',
    'COMFENALCO BOTÓN DE PAGO': 'COMFENALCO',
    'CPMFENALCO BOTON DE PAGO': 'COMFENALCO',
    'COMFENALCO GESTIÓN HUMANA': 'COMFENALCO',
    'COMGFNALCO GESTION HUMANA': 'COMFENALCO',
    'COMFENALCO NAVITRASN': 'COMFENALCO',
    'COMFENLACO NAVITRANS': 'COMFENALCO',
    'COMFENALCO PAGA PACIENTE': 'COMFENALCO',
    'CONVENALCO PAGA PACIENTE': 'COMFENALCO',
    'COMFENLACO PP': 'COMFENALCO',
    'COMFENALCO SER FAMILIAS MAS': 'COMFENALCO',
    'COMFENNALCO FISA': 'COMFENALCO',
    'CONVENIO PAGA PACIENTE': 'CONVENIO',
    'EGRESADA': 'EGRESADO',
    'FAMILIAR EGRASADO': 'EGRESADO',
    'ESTAUDIANTE': 'ESTUDIANTE',
    'ESTUDAINTE': 'ESTUDIANTE',
    'ESTUDIANTES': 'ESTUDIANTE',
    'FONDELCO (LOCERIA COLOMBIANA': 'FONDELCO',
    'FONDELCO (LOCERIA COLOMBIANA)': 'FONDELCO',
    'LICEO SALAZAR Y HERRERA PYP': 'COLEGIO',
    'FUNDACION UDEA': 'UNIVERSIDAD',
    'LAM COSMETICOS': 'EMPRESA',
    'GESTIÓN HUMANA': 'GESTION HUMANA',
    'PARICULAR': 'PARTICULAR',
    'NW STETIC S.A': 'EMPRESA',
    'CONVENIO TLC': 'CONVENIO', 
    'CLINICA OFTALMOLOGICA': 'CLINICA', 
    'IEB PP': 'EMPRESA', 
    'CONVENIO IEB': 'CONVENIO',
    'ACADEMIA SUPERIOR DE ARTES': 'UNIVERSIDAD',
    'BARBARA MICARELLI PP': 'EMPRESA',
    'BIENESTAR 80 %': 'BIENESTAR', 
    'PINARES': 'COLEGIO', 
    'SATRACK PP': 'EMPRESA',
    'COMFENALCO MEDIFARMA': 'COMFENALCO',
    'LAM COSMETICS': 'EMPRESA',
    'COMFENALCO CONTRALORIA': 'COMFENALCO',
    'COMFENALCO FISA': 'COMFENALCO',
    'COGNOX': 'EMPRESA',
    'LICEO SALAZAR Y HERRERA PP': 'COLEGIO',
    'CLINICA OFTALMOLOGICA MEDELLIN': 'CLINICA',
    'COMFENALCO SANTA LUCIA': 'COMFENALCO',
    'COLEGIO LOS PIONEROS PP': 'COLEGIO',
    'COLEGIO BARBARA MICARELLI PP': 'COLEGIO',
    'COLEGIATURA COLOMBIANA DE COSMETOLOGIA': 'COLEGIO',
    'CONVENIO COLEGIO LOS PIONEROS': 'CONVENIO',
    'COMFENALCO SER FAMILIAS': 'COMFENALCO',
    'LICEO SALAZAR Y HERRERA': 'COLEGIO',
    'COLEGIATURA': 'COLEGIO',
    'COLEGIO SALAZAR Y HERRERA': 'COLEGIO',
    'CONVENIO STOP': 'CONVENIO',
    'CONVENIO COLEGIO BARBARA MICARELLI': 'CONVENIO',
    'CONVENIO CLINICA OFTALMOLOGICA': 'CONVENIO',
    'GESTION HUMANA UPB': 'GESTION HUMANA',
    'FUNDACION U DE A PP': 'UNIVERSIDAD',
    'CONVENIO U DE A': 'CONVENIO',
    'COMFENALCO RAPIDO OCHOA': 'COMFENALCO',
    'FAMILIAR EGRESADO': 'EGRESADO',
    'FAMILIAR ESTUDIANTE': 'ESTUDIANTE',
    '143': 'Buenavista',
    '167': 'Cajibío',
    '43': 'Almeida'
}

VALORES_VALIDOS_PROCEDIMIENTO = [
    "Consulta psicológica",
    "Consulta de pareja",
    "Evaluación neuropsicológica",
    "Docencia asistencial"
]

#Num columnas RIPS
COLUMNAS_RIPS = 16

#Columnas RIPS
TIPO_IDENTIFICACION = "tipo de identificacion"
FECHA_CONSULTA = "fecha de consulta"
NRO_AUTORIZACION = "nro de autorizacion"
CODIGO_CONSULTA = "codigo de la consulta"
FINALIDAD_CONSULTA = "finalidad de la consulta"
CAUSA_EXTERNA = "causa externa"
COD_DX_PRINCIPAL = "cod dx principal"
COD_DX_REL_1 = "cod dx rel 1"
COD_DX_REL_2 = "cod dx rel 2"
COD_DX_REL_3 = "cod dx rel 3"
TIPO_DIAGNOSTICO = "tipo de diagnostico"
VALOR_CONSULTA = "valor de la consulta"
VALOR_CUOTA_MODERADORA = "valor cuota moderadora"
VALOR_NETO_PAGAR = "valor neto a pagar"
IDENTIFICACION_ENCRIPTADA = "identificacion encriptada"
ARCHIVOS_ORIGEN = "archivos_origen"


#Num columnas Mensual
COLUMNAS_MENSUAL = 17
#Columnas Mensual
TIPO_IDENTIFICACION_PACIENTE = "Tipo de Identificación del Paciente"
CIUDAD = "Ciudad"
DIRECCION = "Dirección"
BARRIO = "Barrio"
CORREO_ELECTRONICO = "Correo Electrónico"
GENERO = "Género"
FECHA_NACIMIENTO = "Fecha Nacimiento"
EDAD = "Edad"
CONSECUTIVO = "Consecutivo"
ASUNTO = "Asunto"
TIPO_COMPROMISO = "Tipo de Compromiso"
FECHA_CITA = "Fecha de la Cita"
ESTADO_CITA = "Estado de la Cita"
TIPO_PROCEDIMIENTO = "Tipo de Procedimiento"
TIPO_USUARIO = "Tipo de Usuario"
ARCHIVOS_ORIGEN = "archivos_origen"
